name: "Install Knope"
description: "Installs a specified version of Knope, or the latest if unspecified."
branding:
  icon: download
  color: blue
inputs:
  version:
    description: "Specific version to download, defaults to latest."
    required: false
    default: ""
  github-token:
    description: "A token to pass to the GitHub API (e.g., secrets.GITHUB_TOKEN) to avoid rate limiting"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: "Download Knope"
      shell: bash
      run: |
        cd ${{ github.action_path }}
        ./entrypoint.sh "${{ inputs.version }}"
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      env:
        GH_TOKEN: ${{ inputs.github-token }}
